import * as THREE from 'three';
import type {SymbolId} from '../domain/game';
const GLYPH:Record<SymbolId,string>={cherry:'🍒',bell:'🔔',seven:'7'};
export class ReelScene{private renderer:THREE.WebGLRenderer;private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(38,1,.1,100);private reels:THREE.Mesh[]=[];private labels:THREE.Sprite[]=[];private frame=0;constructor(private host:HTMLElement){this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.append(this.renderer.domElement);this.camera.position.set(0,0,7);this.scene.add(new THREE.AmbientLight(0xffd9a3,2));const key=new THREE.PointLight(0xffb347,70);key.position.set(2,3,4);this.scene.add(key);for(let i=0;i<3;i++){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(.82,.82,1.15,48),new THREE.MeshStandardMaterial({color:0xf5e6c8,metalness:.15,roughness:.42}));mesh.rotation.z=Math.PI/2;mesh.position.x=(i-1)*1.75;this.scene.add(mesh);this.reels.push(mesh);const sprite=this.makeLabel('🍒');sprite.position.set(mesh.position.x,0,1);this.scene.add(sprite);this.labels.push(sprite)}this.resize();addEventListener('resize',this.resize);this.loop()}
private makeLabel(text:string){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d')!;x.fillStyle='#fff7e6';x.fillRect(0,0,256,256);x.fillStyle='#8b1118';x.font='bold 150px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,128,128);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c)}));s.scale.set(1.25,1.25,1);return s}
private setLabel(sprite:THREE.Sprite,text:string){const old=sprite.material as THREE.SpriteMaterial;old.map?.dispose();const next=this.makeLabel(text);(sprite.material as THREE.SpriteMaterial).map=(next.material as THREE.SpriteMaterial).map;sprite.material.needsUpdate=true;(next.material as THREE.SpriteMaterial).dispose()}
show(symbols:[SymbolId,SymbolId,SymbolId],payout=0){symbols.forEach((s,i)=>this.setLabel(this.labels[i],GLYPH[s]));this.host.dataset.win=payout>0?'true':'false'}
spin(){this.reels.forEach((r,i)=>r.rotation.x+=.8+i*.08)}
private resize=()=>{const w=this.host.clientWidth||640,h=this.host.clientHeight||420;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
private loop=()=>{this.frame=requestAnimationFrame(this.loop);this.renderer.render(this.scene,this.camera)}
dispose(){cancelAnimationFrame(this.frame);removeEventListener('resize',this.resize);this.renderer.dispose();this.host.replaceChildren()}}
