import './style.css';import{applyUpgrade,createMatch,finish,spin,SPIN_INTERVAL,type UpgradeId}from'./domain/game';import{ReelScene}from'./view/ReelScene';
const app=document.querySelector<HTMLDivElement>('#app')!;app.innerHTML=`<section class="shell"><header><h1>REEL FORGE</h1><div class="timer"><small>残り</small><b id="time">60</b></div><button id="sound" aria-label="音声設定">◉</button></header><div class="scores"><div class="you"><span>あなた</span><strong id="ps">0</strong></div><div class="rival"><span>ライバル</span><strong id="rs">0</strong></div></div><div class="arena"><section class="machine"><div id="reels"></div><div class="pay" id="pay"></div></section><aside class="avatar"><div class="portrait"><div class="mock-face">AI<br><small>RIVAL</small></div><video id="avatar" autoplay playsinline></video></div><p id="line">「60秒。私に勝てる？」</p><div class="mini">ライバルも同じルールで自動スピン</div></aside></div><div class="upgrade" id="upgrade" hidden><p>リール改造を選べ！ <span id="upgradeNo"></span></p><button data-up="steady">🍒 安定型<br><small>チェリーを増やす</small></button><button data-up="jackpot">7 大勝負<br><small>7を増やす</small></button></div><footer><button id="start">60秒で勝ちきれ！</button><p>自動で回る。20秒・40秒でリールを改造。多く稼いだ方が勝ち。</p></footer></section>`;
const q=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;const scene=new ReelScene(q('#reels'));let state=createMatch(),timer=0,elapsed=0,upgradeOpen=false,upgradeCount=0;const lines={lead:['まだ追いつける？','その程度？'],lose:['ちょっと待って、今の強くない？','そこで当てる！？'],win:['ふふ、私の方が上。','いい勝負になってきた。']};
function render(){q('#time').textContent=String(state.remaining).padStart(2,'0');q('#ps').textContent=state.scores.player.toLocaleString();q('#rs').textContent=state.scores.rival.toLocaleString()}
function rivalLine(){const pool=state.scores.player>state.scores.rival?lines.lose:state.scores.player<state.scores.rival?lines.win:lines.lead;q('#line').textContent=`「${pool[Math.floor(Math.random()*pool.length)]}」`}
function openUpgrade(){if(upgradeCount>=2)return;upgradeOpen=true;upgradeCount++;q('#upgradeNo').textContent=`${upgradeCount}/2`;q('#upgrade').hidden=false;setTimeout(()=>{if(upgradeOpen)choose('steady')},4000)}
function choose(id:UpgradeId){if(!upgradeOpen)return;upgradeOpen=false;applyUpgrade(state,'player',id);applyUpgrade(state,'rival',Math.random()>.5?'steady':'jackpot');q('#upgrade').hidden=true;q('#line').textContent=id==='jackpot'?'「大勝負？ 面白いじゃん。」':'「堅実に来たね。」'}
q('#upgrade').addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button[data-up]');if(b)choose(b.dataset.up as UpgradeId)});
q('#start').onclick=()=>{if(state.status==='playing')return;state=createMatch();state.status='playing';elapsed=0;upgradeCount=0;render();q('#start').textContent='対戦中…';timer=window.setInterval(()=>{elapsed+=SPIN_INTERVAL;state.round++;state.remaining=Math.max(0,60-elapsed);scene.spin();const p=spin(state,'player'),r=spin(state,'rival');setTimeout(()=>scene.show(p.symbols,p.payout),350);q('#pay').textContent=p.payout?`+${p.payout.toLocaleString()}`:'';if(p.payout>=1200||r.payout>=1200||elapsed%10===0)rivalLine();if(elapsed===20||elapsed===40)openUpgrade();if(elapsed>=60){clearInterval(timer);finish(state);q('#start').textContent='もう一度勝負';q('#line').textContent=state.winner==='player'?'「……負けた。もう一回。」':state.winner==='rival'?'「私の勝ち。また挑んで。」':'「引き分け？ もう一回で決めよう。」'}render()},SPIN_INTERVAL*1000)};
render();